using UnityEngine;
using Mirror;
using System.Collections.Generic;

public class LSPlayer : NetworkBehaviour
{
    [Header("Lobby & Match State")]
    [SyncVar(hook = nameof(OnNameChanged))] public string playerName = "Unknown Player";
    [SyncVar(hook = nameof(OnReadyChanged))] public bool isReady = false;
    [SyncVar(hook = nameof(OnHostStateChanged))] public bool isGameHost = false;
    [SyncVar(hook = nameof(OnTeamIDChanged))] public int teamID = -1;
    [SyncVar] public bool isAlive = true;

    // To store the original layers generated by JUTPS
    private Dictionary<Transform, int> originalLayers = new Dictionary<Transform, int>();
    private bool isInitialized = false;

    public override void OnStartClient()
    {
        base.OnStartClient();
        // DELAY: Wait 1.5 seconds so JUTPS can completely finish generating its ragdolls and hitboxes
        Invoke(nameof(SaveOriginalLayers), 1.5f);
    }

    private void SaveOriginalLayers()
    {
        foreach (Transform t in GetComponentsInChildren<Transform>(true))
        {
            originalLayers[t] = t.gameObject.layer;
        }
        isInitialized = true;
        Debug.Log($"[LSPlayer] Saved {originalLayers.Count} original layers for {playerName}");
    }

    public override void OnStartLocalPlayer()
    {
        string myName = PlayerPrefs.GetString("PlayerName", "Player " + Random.Range(1000, 9999));
        CmdSetPlayerName(myName);
    }

    public override void OnStartServer()
    {
        if (LSMatchManager.Instance != null) LSMatchManager.Instance.RegisterPlayer(this);
    }

    public override void OnStopServer()
    {
        if (LSMatchManager.Instance != null) LSMatchManager.Instance.UnregisterPlayer(this);
    }

    [Command] public void CmdSetPlayerName(string name) { playerName = name; }
    [Command]
    public void CmdSetReady(bool readyState)
    {
        isReady = readyState;
        if (LSMatchManager.Instance != null) LSMatchManager.Instance.UpdateReadyState();
    }

    void Update()
    {
        // Ensure client is ready and JUTPS layers are saved
        if (!isClient || !isInitialized) return;

        // CONTINUOUS OVERRIDE: We only apply this to REMOTE players on the local screen
        if (!isLocalPlayer)
        {
            var localPlayer = NetworkClient.localPlayer?.GetComponent<LSPlayer>();
            if (localPlayer != null && LSMatchManager.Instance != null)
            {
                bool isTeammate = (LSMatchManager.Instance.currentMode != LSMatchManager.GameMode.Solo) &&
                                  (this.teamID != -1) &&
                                  (this.teamID == localPlayer.teamID);

                // Unity's built-in layer that raycasts should pass through (Layer 2)
                int ignoreLayer = 2;

                foreach (var kvp in originalLayers)
                {
                    if (kvp.Key != null)
                    {
                        int targetLayer = isTeammate ? ignoreLayer : kvp.Value;

                        // Force the layer constantly. If JUTPS tries to revert it, we instantly change it back.
                        if (kvp.Key.gameObject.layer != targetLayer)
                        {
                            kvp.Key.gameObject.layer = targetLayer;
                        }
                    }
                }
            }
        }
    }

    // Dummy function to prevent compiler errors if LSMatchManager still tries to call it
    [Client] public void SetAsTeammate(bool isTeammate) { }

    private void OnNameChanged(string oldName, string newName) { UpdateUI(); }
    private void OnReadyChanged(bool oldReady, bool newReady) { UpdateUI(); }
    private void OnHostStateChanged(bool oldState, bool newState) { UpdateUI(); }
    private void OnTeamIDChanged(int oldID, int newID) { UpdateUI(); }
    private void UpdateUI() { if (LSMatchManager.Instance != null) LSMatchManager.Instance.UpdateLocalUI(); }
}